"""create freebies table

Revision ID: 190040d5c3eb
Revises: 5f72c58bf48c
Create Date: 2025-05-24 18:22:16.084542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190040d5c3eb'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


# revision identifiers, used by Alembic.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freebies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_name', sa.String(), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.Column('dev_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_freebies_company_id_companies')),
        sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_freebies_dev_id_devs')),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freebies')
    # ### end Alembic commands ###